# ---- Base Stage ----
FROM node:24-alpine AS base

# Set the working directory
WORKDIR /app

# Install dependencies only when package files change
COPY package*.json ./
RUN npm ci --legacy-peer-deps

FROM base AS builder
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL
ARG MONGO_URI
ARG AUTH_SECRET=qwer
ARG NEXTAUTH_URL=tyuiop
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_VAPID_PUBLIC_KEY

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV MONGO_URI=${MONGO_URI}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}

# Build the Next.js application for production
RUN npm run build

# ---- Production Stage ----
# This is the final, small image that will be deployed
FROM base AS runner
WORKDIR /app

# Set environment variables for production
ENV NODE_ENV=production

# Copy only the necessary files from the builder stage
# This keeps the final image size small
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Expose the port the app will run on
EXPOSE 3000

# The command to start the Next.js production server
CMD ["node", "server.js"]