# ---- Base Stage ----
# Use a specific version of Node.js for consistency
FROM node:24-alpine AS base

# Set the working directory
WORKDIR /app

# Install dependencies only when package files change
COPY package*.json ./
RUN npm install

# ---- Builder Stage ----
# This stage builds your Next.js application
FROM base AS builder
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# Build the Next.js application for production
RUN npm run build

# ---- Production Stage ----
# This is the final, small image that will be deployed
FROM base AS runner
WORKDIR /app

# Set environment variables for production
ENV NODE_ENV=production

# Copy only the necessary files from the builder stage
# This keeps the final image size small
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Expose the port the app will run on
EXPOSE 3000

# The command to start the Next.js production server
CMD ["node", "server.js"]