# ---- Stage 1: Build ----
FROM node:24-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine

# Set the working directory
WORKDIR /app

# Copy package files again
COPY package*.json ./

# Install ONLY production dependencies to keep the final image small and secure
RUN npm ci --omit=dev

# Copy the compiled application code from the 'builder' stage
COPY --from=builder /app/dist ./dist

# Set the command to run the application using your 'start' script
CMD ["npm", "start"]