FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

FROM node:24-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps --omit=dev
COPY --from=builder /app/dist ./dist

CMD ["npm", "start"]